apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-nginx
spec:
  selector:
    matchLabels:
      run: gateway-nginx
  replicas: 2
  template:
    metadata:
      labels:
        run: gateway-nginx
    spec:
      containers:
      - name: my-nginx
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  labels:
    run: nginx-svc
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    run: gateway-nginx
